
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - sis01
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cadastro_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3309"
    networks:
      - sis01

volumes:
  db_data:

networks:
  sis01:
    driver: bridge
