// SERIAL TEMPERATURA
// IFACI - SENAI - SÃO CARLOS
// CSTADS
// 02/04/2025
// AUTOR: GABRIEL CORTEZ

int SENSOR = 0;  // DEFINE O PINO ANALÓGICO A0 COMO ENTRADA DO SENSOR
float D = 0;    // VARIÁVEL PARA ARMAZENAR O VALOR LIDO DO SENSOR (0-1023)
int T = 0;     //VARIÁVEL PARA ARMAZENAR A TEMPERATURA CALCULADA

void setup (){
  Serial.begin(9600); // INICIA A COMUNICAÇÃO SERIAL COM A TAXA DE 9600 BAUDS
}

void loop(){
  D = analogRead(SENSOR);
  T = (D * 5 * 100)/1023;  // CONVERTE O VALOR LIDO PARA TEMPERATURA
  Serial.print(T);  // ENVIA O VALOR DA TEMPERAURA PARA O SERIAL
  delay(1000); //AGUARDA 1 SEGUNDO ANTES DA PRÓXIMA LEITURA

}

int main(void){
  init (); // INICIA HARDWARE (FUNÇÃO INTERNA DO ARDUINO)
  setup(); // CHAMA A FUNÇÃO SETUP
  for (;;) // LOOP INFINITO
   loop(); // CHAMA CONTINUAMENTE A FUNÇÃO LOOP()

   return 0;
}